### ISSUE TITLE
Strange pinout for LCD connector to LCS12864 board

### ISSUE THREAD

**Issue by TD-er** [ralf-e/ANET-3D-Board-V1.0#2]
I was just looking into the schematics and they are quite interesting  and informative.
But I was wondering if either the labeling or the pinout of the pins to the LCD connector on the LCD12864 board are correct?
EXT-RX1 and EXT-TX1 are said to be connected to the encoder.
EXT-SCL to the reset switch and EXT-SDA to the speaker.

And the EXT-A1 , -A3 and -A4 do the actual display communication.
It looks like the pinout is correct, but then where are the labels coming from?

**Comment by ralf-e** [comment]
These labels are the Arduino-"pins"
https://github.com/SkyNet3D/anet-board/blob/master/hardware/anet/avr/variants/sanguino/pins_arduino.h
